---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # KAFKA_LOG4J_LOGGERS: "kafka.controller=TRACE,kafka.request.logger=WARN"
      # KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      # KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     
  streams:
    build: 
      context: ./streams
    restart: always
    volumes:
      - "./streams:/app"


  batch:
    build: 
      context: ./batch
    # restart: always
    volumes:
      - "./batch:/app"
    container_name: batch_data

  # kindle_app:
  #   build:
  #     context: ./kindle
  #   depends_on:
  #     - broker
  #   volumes:
  #     - ./kindle:/app
  #   container_name: kindle_cont
  # mongo:
  #   image: mongo
  #   # restart: always
      # command: mongod --quiet --logpath /dev/null
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example


  spark:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: 'master'
      # SPARK_RPC_AUTHENTICATION_ENABLED: no
      # SPARK_RPC_ENCRYPTION_ENABLED: no
      # SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      # SPARK_SSL_ENABLED: no
    ports:
      - '8080:8080'
      - "7077:7077"

  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: 'worker'
      SPARK_MASTER_URL: 'spark://spark:7077'
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
      # SPARK_RPC_AUTHENTICATION_ENABLED: no
      # SPARK_RPC_ENCRYPTION_ENABLED: no
      # SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      # SPARK_SSL_ENABLED: no

  # buy_app:
  #   build:
  #     context: ./buy
  #   volumes:
  #     - ./buy:/app
  #   container_name: buy
  
  # aggregate_app:
  #   build:
  #     context: ./aggregate
  #   volumes:
  #     - ./aggregate./app
  #   container_name: aggregate_cont

  
  
  # raw-data_app:
  #   build:
  #     context: ./raw
    # volumes:
      # - "./raw:/app"
  #   container_name: raw_cont

  # sell_app:
  #   build:
  #     context: ./sell
  #   volumes:
    #   - "./sell:/app"
  #   container_name: sell_cont

  # stoploss_app:
  #   build:
  #     context: ./stoploss
  #   volumes:
  #     - "./stoploss:./app"
  #   container_name: stoploss_cont
  

  