---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     
  mongo:
    image: mongo
    # restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27000:27017"
    
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: 'master'
    ports:
      - '8080:8080'
      - "7077:7077"

  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: 'worker'
      SPARK_MASTER_URL: 'spark://spark:7077'
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1


  streams:
    build: 
      context: ./streams
    restart: always
    volumes:
      - "./streams:/app"

  kindle_app:
    build:
      context: ./kindle
    restart: always
    depends_on:
      - broker
    volumes:
      - ./kindle:/app
    container_name: kindle_cont
  
  

  

  