name: Deploy to Docker Hub

description: Deploy to Docker Hub

on:
  push:
    branches:
      - master
jobs:

  steps:
    - name: Login to Docker Hub
      shell: bash
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build and push
      shell: bash
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest


# github action file to deploy to dorkerimages